# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_auto_20180716_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
