# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 00:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0005_remove_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
