# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_user_set', to='twitter.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_user_set', to='twitter.TwitterUser'),
        ),
    ]
